version: '2'

services:

  profiles-frontend:
    image: "nhsuk/profiles:${DOCKER_IMAGE_TAG}"
    environment:
      CACHE_TIMEOUT_SECONDS: 1800
      ES_HOST: ${ES_HOST}
      ES_INDEX: ${ES_INDEX}
      ES_PORT: ${ES_PORT}
      GOOGLE_ANALYTICS_TRACKING_ID: ${GOOGLE_ANALYTICS_TRACKING_ID}
      HOTJAR_ANALYTICS_TRACKING_ID: ${HOTJAR_ANALYTICS_TRACKING_ID}
      NODE_ENV: production
      WEBTRENDS_ANALYTICS_TRACKING_ID: ${WEBTRENDS_ANALYTICS_TRACKING_ID}
    labels:
      io.rancher.container.pull_image: always
      prometheus.monitoring: true
      prometheus.port: 3000
      traefik.backend: ${RANCHER_STACK_NAME}-profiles-frontend
      traefik.enable: true
      traefik.frontend.auth.basic: ${BASIC_AUTH}
      traefik.frontend.rule: $TRAEFIK_RULE
      traefik.port: 3000
    logging:
      driver: splunk
      options:
        splunk-format: json
        splunk-insecureskipverify: "true"
        splunk-source: profiles
        splunk-sourcetype: docker
        splunk-token: ${SPLUNK_HEC_TOKEN}
        splunk-url: ${SPLUNK_HEC_URL}
        splunk-verify-connection: "false"
        tag: "{{`{{.ImageName}} {{.Name}} {{.FullID}}`}}"
